language: python
python:
  - 2.7
  - 3.6
services:
  - docker
sudo: required
install:
  - pip install -r requirements-doc.txt
script:
  - docker run -d -p 127.0.0.1:8080:5000 --name monitoring checkmk/check-mk-raw:1.5.0p6
  - sleep 60
  - docker exec -u cmk monitoring bash -c "mkdir -p /omd/sites/cmk/var/check_mk/web/automation/; echo automation-secret > /omd/sites/cmk/var/check_mk/web/automation/automation.secret"
  - CHECK_MK_URL=http://localhost:8080/cmk/check_mk CHECK_MK_USER=automation CHECK_MK_SECRET=automation-secret python setup.py test 
  - cd doc
  - pydocmd build
  - cd ..
deploy:
 provider: pages
 skip_cleanup: true
 github_token: $GITHUB_TOKEN
 local_dir: doc/_build/site
 on:
   branch: master
